### ISSUE TITLE
Speed degradation

### ISSUE THREAD

**Issue by advanpix** [CESNET/GPUJPEG#42]
Thank you for the hard work developing and maintaining the project. 

I used the library several years ago, and decided to upgrade to current master yesterday. 
To my surprise I found that encoding has become ~30% slower compared to the previous version. 
(I use the same 1080Ti board and can test previous and new versions side by side).

After quick check of the source code, I see that quite a lot of of initializations/allocations are now included in `gpujpeg_encoder_encode`.

For example, one of the heaviest functions  - `gpujpeg_coder_init_image`. Huge part of this function executes on each call to `gpujpeg_encoder_encode`, even if all encoder's buffers were properly pre-allocated.

Moreover, if user wants to pre-allocate the internals of the encoder (to avoid re-allocations in `gpujpeg_encoder_encode`) by using the function `gpujpeg_encoder_allocate` - it doesn't improve anything.

Just because function `gpujpeg_encoder_allocate` completely ignores the input image size supplied by user. Instead it just tries to guess the width and height from some abstract number of `pixels`:
```
    // Set image size from pixels
    struct gpujpeg_image_parameters tmp_param_image;
    tmp_param_image = *param_image;
    tmp_param_image.width = (int) sqrt((float) pixels);
    tmp_param_image.height = (pixels + tmp_param_image.width - 1) / tmp_param_image.width;

```
Naturally, after this kind of "pre-allocation" for incorrect image size, internal buffers of encoder must be re-allocated properly once `gpujpeg_encoder_encode` is called.

So basically, now there is no way to make all the pre-allocations beforehand and then just supply the input image to encoder for (fast) compression, as it was before.

This is (huge) speed regression from the lightweight architecture of older version of GPUJPEG. 
Please consider giving user the possibility to pre-allocate everything once (e.g. on encoder creation).

By simply changing the code of `gpujpeg_encoder_allocate` (to use the user's image size) and by removing the `gpujpeg_coder_init_image` from `gpujpeg_encoder_encode` - I have got immediate speed boost of ~15-20%.
Still, slower than previous version(s) - but this clearly demonstrates that current approach leads to speed degradation.

Please make the `gpujpeg_encoder_encode` as lightweight as possible with all the pre-allocations on the time when encoder is created (as it was before).

**Comment by MartinPulec** [comment]
Hi Pavel,
confirmed. Can you for a reference write the commit ID you used previously and also typical image properties you use?

Thanks,
Martin

**Comment by advanpix** [comment]
Hi Martin,

Sorry, I don't know the commit ID of the older version I have (I stripped off the github files back then).
The last change time of files in `libgpujpeg` is April-October 2017.

This was the times when encoder creation function had following semantic:
`gpujpeg_encoder_create(struct gpujpeg_parameters* param, struct gpujpeg_image_parameters* param_image);`

I am using images of various properties, but particular images I tested were:
```
image_params.comp_count      = 1;             // 1 - Grayscale
image_params.color_space     = GPULAC5_RGB;
image_params.pixel_format    = GPULAC5_U8;
image_params.width           = 15776;
image_params.height          = 2048;
```

Corresponding parameters for the previous version (there is no `pixel_format` field, but `sampling_factor`):

```
image_params.comp_count      = 1;             // 1 - Grayscale
image_params.color_space     = GPUJPEG_RGB;
image_params.sampling_factor = GPUJPEG_4_4_4;
image_params.width           = 15776;
image_params.height          = 2048;
```

In both cases encoder parameters were:
```
encoder_params.restart_interval = 8;
encoder_params.segment_info     = 0;
encoder_params.verbose          = 0;
```

Let me know if I can help you somehow,
Pavel.

**Comment by MartinPulec** [comment]
Ok, it should be no problem. There was one significant merge that introduced the changes so it might be no problem to track approximately the performance in the original branch. Thanks for the properties for a reference, I'll take a look. Also thank you for tracking the problem - I'll start with skipping the body of `gpujpeg_coder_init_image` and we will see then.

**Comment by MartinPulec** [comment]
Hi Pavel,
I've pushed a change more or less according to your recommendations and the performance looks more or less the same as 85b6bab7 - it is from 2018 but the relevant changes since 2017 were mostly only a maintenance. Please let me know if you still get somehow worse performance than in some former revisions.

Thanks,
Martin

**Comment by advanpix** [comment]
Hi Martin,

New changes bring significant improvement, but still speed is lower compared to the old version I have.

If I compress the same image 15776 x 2048 three times in a row with older version I see the following timings:
```
0.009 sec
0.008 sec
0.008 sec
```

Current master gives:
```
0.013 sec
0.010 sec
0.011 sec
```
Last two iterations suffer from  ~25% drop in speed (I do not count the first run since current version runs initialization there).

I supply image already in GPU memory (GPUJPEG_ENCODER_INPUT_GPU_IMAGE) to new encoder. 
For older version I use image in host-allocated memory. Still it is faster!

I attached the older GPUJPEG version I am comparing to (should have done this before - sorry). Would appreciate your comments very much. 

[GPUJPEG-2017.zip](https://github.com/CESNET/GPUJPEG/files/4856965/GPUJPEG-2017.zip)

**Comment by MartinPulec** [comment]
Well, I am a bit confused now. I've compared the version you have provided with the current and except of first image, which has significantly higher processing time, the numbers between the two versions are comparable. The different time can furthermore be caused by different measuring (previously - cuda events, currently host time).

Would it be possible to provide an exaple which demonstrates the difference? Best would be using the test application if possible, alternatively a minimal working example?

I've tested with following command in the end (the **img.r** image contains a white noise):

    gpujpeg -s 15776x2048 -e ~/img.r img.jpg --verbose -n 1000

And measured a wall clock time. The times were very close each other. Assuming that I am doing everything right. 

I can also test with image already on GPU but it looks like it is not crucial.

Thanks a lot!
Martin

**Comment by advanpix** [comment]
I use CUDA 10.2 SDK and its compiler. It allows at least `--generate-code arch=compute_30,code=sm_30` , so that CC 2.0 is not supported.

Here is detailed timings collected by encoder. Same image was encoded 4 times in a row. Only timings for the last three runs are shown.

Old version:
```
 -Copy To Device:          2.69 ms
 -Preprocessing:           0.18 ms
 -DCT & Quantization:      0.89 ms
 -Huffman Encoder:         2.80 ms
 -Copy From Device:        0.56 ms
 -Stream Formatter:        0.00 ms
Encode Image GPU:          3.97 ms (only in-GPU processing)

 -Copy To Device:          2.69 ms
 -Preprocessing:           0.18 ms
 -DCT & Quantization:      0.89 ms
 -Huffman Encoder:         2.80 ms
 -Copy From Device:        0.58 ms
 -Stream Formatter:        0.00 ms
Encode Image GPU:          3.96 ms (only in-GPU processing)

 -Copy To Device:          2.78 ms
 -Preprocessing:           0.18 ms
 -DCT & Quantization:      0.89 ms
 -Huffman Encoder:         2.80 ms
 -Copy From Device:        0.55 ms
 -Stream Formatter:        0.00 ms
Encode Image GPU:          4.02 ms (only in-GPU processing)
```

New:
```
 -Preprocessing:           0.01 ms
 -DCT & Quantization:      0.01 ms
 -Huffman CPU Encoder:     0.00 ms
 -Huffman Encoder:         3.94 ms
 -Copy From Device:        0.53 ms
 -Stream Formatter:        0.93 ms
Encode Image GPU:          4.49 ms (only in-GPU processing)

 -Preprocessing:           0.01 ms
 -DCT & Quantization:      0.01 ms
 -Huffman CPU Encoder:     0.00 ms
 -Huffman Encoder:         4.01 ms
 -Copy From Device:        0.52 ms
 -Stream Formatter:        0.89 ms
Encode Image GPU:          4.55 ms (only in-GPU processing)

 -Preprocessing:           0.01 ms
 -DCT & Quantization:      0.01 ms
 -Huffman CPU Encoder:     0.00 ms
 -Huffman Encoder:         3.97 ms
 -Copy From Device:        0.53 ms
 -Stream Formatter:        0.90 ms
Encode Image GPU:          4.51 ms (only in-GPU processing)
```

Apparently preprocessing, DCT & quantization became faster in new version. But Huffman encoder (GPU) is a way slower now. Stream formatter (CPU) is also slower. 

As I see, Huffman encoding on GPU was changed quite a lot since the old version. Maybe this is the reason? 

Please note, new version doesn't measure timings of preprocessing, DCT & Quantization and Huffman encoder (GPU).
I just copied relevant code from an old version to do this.

**Comment by MartinPulec** [comment]
> Please note, new version doesn't measure timings of preprocessing, DCT & Quantization and Huffman encoder (GPU).
I just copied relevant code from an old version to do this.

Well. I am not sure if this is a good idea because now it is really not clear what are the relevant values and I am not sure how to compare to my version (without the code) - you just reverted the commit c97540b or it is done otherwise?

(I may return there the previous measurements then again (but without the synchronization for which it was removed).)

Would it be possible to run something like several thousands iteration on each version and compare a wallclock time (eg. measured by `time`)?

    time ./gpujpeg -s 15776x2048 -e img.r img.jpg --verbose -n 1000

Also I'd suggest compiling both versions with eg. to ensure that the compile flags are the same:

    nvcc -Isrc -I. `find src -type f \( -name '*.c' -o -name '*.cpp' -o -name '*.cu'  \)` -o gpujpeg

Last, would it be possible to share the appropriate picture? Or try it on some picture from the repo, eg. colors/image_bt709_422.yuv? (You'll need `-f 4:2:2` for old and `-f 422-u8-p1020` opt in a new version).

**Comment by advanpix** [comment]
I just wrapped the Huffman encoding with GPUJPEG_CUSTOM_TIMER_START/STOP:

```
        // Perform huffman coding
        GPUJPEG_CUSTOM_TIMER_START(encoder->def);
        unsigned int output_size;
        if ( gpujpeg_huffman_gpu_encoder_encode(encoder, &output_size) != 0 ) {
            fprintf(stderr, "[GPUJPEG] [Error] Huffman encoder on GPU failed!\n");
            return -1;
        }
        GPUJPEG_CUSTOM_TIMER_STOP(encoder->def);
        coder->duration_huffman_coder = GPUJPEG_CUSTOM_TIMER_DURATION(encoder->def);

```
Same for preprocessing and DCT & Quantization.
Can you just measure timings of these functions in the same way? What timings do you get compared to old version?

Wall clock is not informative. We need to measure each function to find what became slower.

**Comment by MartinPulec** [comment]
For reference, just pasting my results on *NVIDIA 2080 Ti*. The picture properties are different from yours but it is in the repository so maybe it is better to deal with the same image if possible.

## old
```
$ /usr/local/cuda-10.2/bin/nvcc -Isrc -I. `find src -type f \( -name '*.c' -o -name '*.cpp' -o -name '*.cu'  \)` -o gpujpeg-old
$ time ./gpujpeg-old -s 1920x1080 -f 4:2:2 -e <path_to_gpujpeg_repo>/colors/image_bt709_422.yuv img.jpg --verbose -n 1000
[... omitted ...]
Iteration #1000:
 -Copy To Device:          0.34 ms
 -Preprocessing:           0.05 ms
 -DCT & Quantization:      0.05 ms
 -Huffman Encoder:         0.10 ms
 -Copy From Device:        0.06 ms
 -Stream Formatter:        0.10 ms
Encode Image GPU:          0.20 ms (only in-GPU processing)
Encode Image Bare:         0.32 ms (without copy to/from GPU memory)
Encode Image:              0.72 ms

Save Image:                0.14 ms
Compressed Size:         125420 bytes [img.jpg]

real    0m1.082s
user    0m0.633s
sys     0m0.339s

```

## new
```
$ /usr/local/cuda-10.2/bin/nvcc -Isrc -I. `find src -type f \( -name '*.c' -o -name '*.cpp' -o -name '*.cu'  \)` -o gpujpeg-new
$ time ./gpujpeg-new -s 1920x1080 -f 422-u8-p1020 -e colors/image_bt709_422.yuv img.jpg --verbose -n 1000
[... omitted ...]
Iteration #1000:
Using faster kernel for preprocessor (precompiled 1x1, 1x1, 1x1).
 -Huffman CPU Encoder:     0.00 ms
 -Stream Formatter:        0.10 ms
Encode Image GPU:          0.55 ms (only in-GPU processing)
Encode Image:              0.66 ms

Save Image:                0.12 ms
Compressed Size:         123484 bytes [img.jpg]

real    0m1.051s
user    0m0.590s
sys     0m0.369s
```

As you can see, the results are nearly the same for me.

**Comment by advanpix** [comment]
Well, new version is ~2 times slower according to your tests:
Encode Image GPU:          0.20 ms (only in-GPU processing)
vs.
Encode Image GPU:          0.55 ms (only in-GPU processing)

Also your timings for new version do not include Huffman Encoder (GPU) ,  DCT & Quantization and preprocessing.

**Comment by MartinPulec** [comment]
> I just wrapped the Huffman encoding with GPUJPEG_CUSTOM_TIMER_START/STOP:
> 
> ```
>         // Perform huffman coding
>         GPUJPEG_CUSTOM_TIMER_START(encoder->def);
>         unsigned int output_size;
>         if ( gpujpeg_huffman_gpu_encoder_encode(encoder, &output_size) != 0 ) {
>             fprintf(stderr, "[GPUJPEG] [Error] Huffman encoder on GPU failed!\n");
>             return -1;
>         }
>         GPUJPEG_CUSTOM_TIMER_STOP(encoder->def);
>         coder->duration_huffman_coder = GPUJPEG_CUSTOM_TIMER_DURATION(encoder->def);
> ```
> 
> Same for preprocessing and DCT & Quantization.

Ok, I understand, but it is measuring now system time, so it is no longer relevant.

> Can you just measure timings of these functions in the same way? What timings do you get compared to old version?

In future perhaps yes, currently it is done otherwise.

> Wall clock is not informative. We need to measure each function to find what became slower.

I don't entirely agree - from my observation it is not slower as a whole and I think that it is worth checking. It is the truth is that the fine measurements would be nice but it is just not now.

**Comment by MartinPulec** [comment]
> Well, new version is ~2 times slower according to your tests:
> Also your timings for new version do not include Huffman Encoder (GPU) , DCT & Quantization and preprocessing.

But that comparison is not relevant between the versions. Both versions yield something like 1 ms per iteration.

**Comment by advanpix** [comment]
GPU code in new version is slower compared to old version. This is the thing. Your tests show this explicitly.
All secondary code (which run on CPU) can be optimized to the bones - storing input image in GPU memory directly, etc. etc.

So that "it is not slower as a whole" has no meaning. GPU code is the heart of the library and it is has became slower by approx. 2 times.

**Comment by mpiatka** [comment]
Hi!
The new version is actually slightly faster. It's just that, as Martin already mentioned, the way the times are measured changed so it makes no sense to compare them directly.

You can clearly see from the screenshots below that the performance actually improved in the new version.
![gpujpeg-new](https://user-images.githubusercontent.com/3661509/86340088-b4834d00-bc54-11ea-8dea-1a854174167a.png)
![gpujpeg-old](https://user-images.githubusercontent.com/3661509/86340090-b51be380-bc54-11ea-8545-e9e9341e910c.png)

**Comment by advanpix** [comment]
Even if we compare "overall" timings, this contradicts to what I [see](https://github.com/CESNET/GPUJPEG/issues/42#issuecomment-652801855) :

Encode Image GPU:          3.97 ms (only in-GPU processing)
vs. 
Encode Image GPU:          4.49 ms (only in-GPU processing)

And what was [provided](https://github.com/CESNET/GPUJPEG/issues/42#issuecomment-652823851) by Martin in his tests:

Encode Image GPU: 0.20 ms (only in-GPU processing) 
vs. 
Encode Image GPU: 0.55 ms (only in-GPU processing).

Overall, I have been using the library for quite a few years. I see reproducible drop in performance in new version compared to older one. I found several reasons of this drop. First was that initialization functions were included during encoding (now fixed). 
Second one is that Huffman encoding (GPU) and stream formatters have became slower. This can be seen in tests, as another Martin showed and I see on my side. 

Maybe I am missing something here, or this is matter of GPU board (I am using 1080Ti).

**Comment by MartinPulec** [comment]
I've just pushed changes that measure the durations in a comparable way as the previous version. Results follow:

## Old
```
Iteration #1000:
 -Copy To Device:          0.34 ms
 -Preprocessing:           0.05 ms
 -DCT & Quantization:      0.05 ms
 -Huffman Encoder:         0.10 ms
 -Copy From Device:        0.06 ms
 -Stream Formatter:        0.10 ms
Encode Image GPU:          0.20 ms (only in-GPU processing)
Encode Image Bare:         0.33 ms (without copy to/from GPU memory)
Encode Image:              0.73 ms

Save Image:                0.12 ms
Compressed Size:         125420 bytes [img.jpg]
```

## Current
```
Iteration #1000:
Using faster kernel for preprocessor (precompiled 1x1, 1x1, 1x1).
 -Copy To Device:          0.34 ms
 -Preprocessing:           0.04 ms
 -DCT & Quantization:      0.04 ms
 -Huffman Encoder:         0.08 ms
 -Copy From Device:        0.05 ms
 -Stream Formatter:        0.11 ms
Encode Image GPU:          0.17 ms (only in-GPU processing)
Encode Image Bare:         0.28 ms (without copy to/from GPU memory)
Encode Image:              0.68 ms

Save Image:                0.13 ms
Compressed Size:         123484 bytes [img.jpg]
```

As you can see, the numbers are not worse but as @mpiatka noticed, it is even slightly better. (Which is mostly due to use of streams/async calls I guess.)

If you are still encountering some regression, we will be glad if you let us know but I'd ask you for some details how to reproduce it.

**Comment by advanpix** [comment]
Thank you for the test. Could you please do the same comparison (old vs. current) for the attached image in your environment ?
This is 8bpp grayscale image of 15776x2048 size. I use the following settings for encoding:

Old
```
image_params.comp_count      = 1;             // 1 - Grayscale
image_params.color_space     = GPUJPEG_RGB;
image_params.sampling_factor = GPUJPEG_4_4_4;
image_params.width           = 15776;
image_params.height          = 2048;
```

Current
```
image_params.comp_count      = 1;             // 1 - Grayscale
image_params.color_space     = GPULAC5_RGB;
image_params.pixel_format    = GPULAC5_U8;
image_params.width           = 15776;
image_params.height          = 2048;
```

In both cases encoder parameters are (please try different quality parameters if possible):
```
encoder_params.restart_interval = 8;
encoder_params.segment_info     = 0;
encoder_params.verbose          = 0;
encoder_params.quality          = 75; // 90, 85, 80, 75 
```

Thank you,
Pavel.

[example.pgm.zip](https://github.com/CESNET/GPUJPEG/files/4867415/example.pgm.zip)

**Comment by MartinPulec** [comment]
[Here](https://github.com/CESNET/GPUJPEG/files/4882959/log.zip) it is.

**Comment by advanpix** [comment]
Hi Martin, thank you for your time!

Btw, the tags "unable-to-reproduce" and "invalid" are not correct. The slow-down initially reported in this thread was confirmed and fixed. It was significant, because initialization code was called on each call to `gpujpeg_encoder_encode`. 

The slow-down reported later in the thread still occurs on older boards like 1080Ti, and it is still noticeable. 
Good thing that it is not observed on 2080Ti, but it doesn't make my report "invalid" or of lesser value for other users.

**Comment by MartinPulec** [comment]
Hi,

well, it depends - "unable to reproduce" is definitely valid from my point of view.

> The slow-down reported later in the thread still occurs on older boards like 1080Ti, and it is still noticeable.
> Good thing that it is not observed on 2080Ti, but it doesn't make my report "invalid" or of lesser value for other users.

I see, ok, But the thing is that you didn't provide data proving that. I've now quick tested on 1080 Ti and it is behaving very similarly as on 2080 Ti (it means the times very similar for both versions). I cannot deny that a problem/regression may occur that I am not able to reproduce. So the label rather relates to the report, not the problem. If you have some more relevant data, feel free to reopen the issue.
